# @package _global_
# Add Pytorch profiler
trainer:
  profiler:
    _target_: pytorch_lightning.profilers.PyTorchProfiler
    on_trace_ready:
      _target_: torch.profiler.tensorboard_trace_handler
      dir_name: tb/profiler
