# @package _global_
evaluation_metrics:
  dual_binding_hits:
    _target_: routed.ocl.metrics.BindingHits
    prediction_path: object_decoder.dual_masks_as_image
    target_path: input.instance_mask_v2
    selected_indices_path: input.selected_indices
    use_threshold: false
    matching: best_overlap
    ignore_overlaps: false
  dual_instance_ari:
    _target_: routed.ocl.metrics.ARIMetric
    prediction_path: object_decoder.dual_masks_as_image
    target_path: input.instance_mask
    foreground: false
    convert_target_one_hot: true
    ignore_overlaps: true
  dual_instance_mbo:
    _target_: routed.ocl.metrics.UnsupervisedMaskIoUMetric
    prediction_path: object_decoder.dual_masks_as_image
    target_path: input.instance_mask
    use_threshold: false
    matching: best_overlap
    ignore_overlaps: true
