# @package _global_
evaluation_metrics:
  slot_occupancy:
    _target_: routed.ocl.metrics.SlotMaskOccupancy
    masks_path: masks_resized
    threshold: 0.02
  slot_mask_entropy:
    _target_: routed.ocl.metrics.CategoricalEntropy
    tensor_path: masks_resized
    dim: 1
