# @package _global_
# Metrics for object discovery on COCO/VOC with instance masks.
evaluation_metrics:
  instance_ari:
    _target_: routed.ocl.metrics.ARIMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    foreground: false
    convert_target_one_hot: true
    ignore_overlaps: true
  instance_ari_min2:
    _target_: routed.ocl.metrics.ARIMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    foreground: false
    convert_target_one_hot: true
    ignore_overlaps: true
    min_true_classes: 2
  instance_iou:
    _target_: routed.ocl.metrics.UnsupervisedMaskIoUMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
  instance_mbo:
    _target_: routed.ocl.metrics.AverageBestOverlapMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
  instance_recovery:
    _target_: routed.ocl.metrics.BestOverlapObjectRecoveryMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
  instance_corloc:
    _target_: routed.ocl.metrics.MaskCorLocMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
