# @package _global_
# Preprocessing for evaluating on ClevrTex
dataset:
  eval_transforms:
    03_preprocessing:
      _target_: ocl.transforms.SimpleTransform
      transforms:
        image:
          _target_: torchvision.transforms.Compose
          transforms:
            - "${lambda_fn:'lambda image: image.copy()'}"
            - _target_: torchvision.transforms.ToTensor
            - _target_: torchvision.transforms.Resize
              _convert_: all
              size: [224, 224]
              interpolation: ${torchvision_interpolation_mode:BICUBIC}
            - "${lambda_fn:'lambda image: image.clamp(0.0, 1.0)'}"
            - _target_: torchvision.transforms.Normalize
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
        mask:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: ocl.preprocessing.ToGrayscale
            - _target_: ocl.preprocessing.IntegerToOneHotMask
              max_instances: 10
              ignore_typical_background: false
            - _target_: ocl.preprocessing.DenseMaskToTensor
            - _target_: ocl.preprocessing.CheckFormat
              shape: [11, 240, 240]
              one_hot: true
      batch_transform: false
