# The coco2017 dataset with instance, stuff and caption annotations.
_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/entityseg/train/shard-{000000..000102}.tar"
train_size: 9992
val_shards: "${oc.env:DATASET_PREFIX}/entityseg/val/shard-{000000..000015}.tar"
val_size: 1432
test_shards: "${oc.env:DATASET_PREFIX}/entityseg/val/shard-{000000..000015}.tar"
test_size: 1432
use_autopadding: true
