_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/sam_dataset/shard-{000000..000191}.tar"
train_size: 5000000
val_shards: "${oc.env:DATASET_PREFIX}/coco2017/val/shard-{000000..000017}.tar"
val_size: 5000
test_shards: "${oc.env:DATASET_PREFIX}/coco2017/test/shard-{000000..000126}.tar"
test_size: 40670
use_autopadding: true

train_transforms:
  00_1_rename_fields:
    _target_: ocl.transforms.Map
    transform:
      _target_: ocl.preprocessing.RenameFields
      mapping:
        jpg: image
    fields: [jpg]
    # While this could easily be a batch transform,
    # but many preprocessing steps assume different naming.
    # Thus apply rename prior to their application.
    batch_transform: false
# eval_transforms:
#   00_1_rename_fields:
#     _target_: ocl.transforms.Map
#     transform:
#       _target_: ocl.preprocessing.RenameFields
#       mapping:
#         video: image
#         segmentations: mask
#     fields: [video, segmentations]
#     # While this could easily be a batch transform,
#     # but many preprocessing steps assume different naming.
#     # Thus apply rename prior to their application.
#     batch_transform: false
#   00_2_adapt_mask_format:
#     _target_: ocl.transforms.SimpleTransform
#     transforms:
#       mask:
#         _target_: ocl.preprocessing.IntegerToOneHotMask
#         output_axis: -4
#         max_instances: 10
#         ignore_typical_background: false
#     batch_transform: false
#   02_sample_frames:
#     _target_: ocl.transforms.SampleSlices
#     fields:
#       - image
#       - mask
#     n_slices_per_input: -1
#     dim: 0
#     seed: 457834753
#     shuffle_buffer_size: 1
